title: Anushree Dhople 
logo: "/images/logo.png?raw=true" # your photo (or logo) here
description: > 
  Machine Learning Engineer 
  <br><br>
  10 years of leadership in Software Engineering in Healthcare & Education. Senior Technical Architect with global experience in
  developing Agile product and product teams.
  <br><br>
  Masters in Data Science (UIUC) with specialization in Machine Learning, focussing on bringing the power of ML to the Healthcare industry. 
  <a href="https://www.linkedin.com/in/anushree-dhople-b765541/">View My LinkedIn Profile</a> 
  
theme: jekyll-theme-minimal
google_analytics: UA-000000-0 # your Google Analytics tracking ID here
